#!/usr/bin/env bash
# dnsmasq entrypoint — generates a minimal dnsmasq.conf from environment
# variables and starts the daemon in the foreground.
set -euo pipefail

# ── Resolve SERVER_HOST ────────────────────────────────────────────────────────
if [[ -z "${SERVER_HOST:-}" ]]; then
    SERVER_HOST=$(ip -4 route get 1.1.1.1 2>/dev/null \
        | awk '/src/{for(i=1;i<=NF;i++) if($i=="src") {print $(i+1); exit}}')
fi
if [[ -z "${SERVER_HOST:-}" ]]; then
    echo "ERROR: Cannot determine SERVER_HOST. Set it explicitly in .env." >&2
    exit 1
fi

INTERFACE="${INTERFACE:-eth0}"
DHCP_RANGE="${DHCP_RANGE:-192.168.1.100,192.168.1.200,12h}"
WEBUI_PORT="${WEBUI_PORT:-8080}"

echo "=== EVE-OS iPXE dnsmasq DHCP service ==="
echo "  Interface  : ${INTERFACE}"
echo "  DHCP range : ${DHCP_RANGE}"
echo "  TFTP server: ${SERVER_HOST}"
echo "  Boot file  : undionly.kpxe"
echo ""

# ── Write dnsmasq.conf ─────────────────────────────────────────────────────────
CONF=/tmp/dnsmasq.conf
cat > "${CONF}" <<DNSMASQ
# Generated by eve-ipxe dnsmasq entrypoint
interface=${INTERFACE}
bind-interfaces

# DHCP
dhcp-range=${DHCP_RANGE}
dhcp-no-override

# Push default gateway if set
$([ -n "${DHCP_ROUTER:-}" ] && echo "dhcp-option=option:router,${DHCP_ROUTER}" || echo "# DHCP_ROUTER not set")

# Push DNS server if set
$([ -n "${DHCP_DNS:-}" ] && echo "dhcp-option=option:dns-server,${DHCP_DNS}" || echo "# DHCP_DNS not set")

# ── PXE / iPXE boot ────────────────────────────────────────────────────────────
# Point legacy BIOS PXE clients to our TFTP server & the iPXE binary.
# iPXE clients that already have an embedded script will chain to HTTP.

# TFTP server address (option 66)
dhcp-option=66,${SERVER_HOST}

# BIOS PXE: serve undionly.kpxe which bootstraps into iPXE, then boot.ipxe
dhcp-boot=undionly.kpxe,${SERVER_HOST},${SERVER_HOST}

# UEFI x86_64: serve ipxe.efi
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:efi-x86_64,ipxe.efi,${SERVER_HOST},${SERVER_HOST}

# UEFI arm64: serve ipxe-arm64.efi
dhcp-match=set:efi-arm64,option:client-arch,11
dhcp-boot=tag:efi-arm64,ipxe-arm64.efi,${SERVER_HOST},${SERVER_HOST}

# If the client is already running iPXE, send it straight to the menu script
# via HTTP (much faster than TFTP for large files).
dhcp-userclass=set:ipxe,iPXE
dhcp-boot=tag:ipxe,http://${SERVER_HOST}:${WEBUI_PORT}/ipxe/boot.ipxe

# Logging
log-queries
log-dhcp
DNSMASQ

echo "Generated dnsmasq.conf:"
cat "${CONF}"
echo ""

exec dnsmasq --conf-file="${CONF}" --no-daemon --log-facility=- "$@"
