"""
DHCP server manager — controls the eve-ipxe-dnsmasq container via the
Docker Engine API (Unix socket) and manages the dnsmasq configuration.
"""
from __future__ import annotations

import json
import logging
import re
from pathlib import Path

import httpx

from app.config import get_settings

logger = logging.getLogger(__name__)

DOCKER_SOCKET = "/var/run/docker.sock"
CONTAINER_NAME = "eve-ipxe-dnsmasq"

# Fields persisted to dhcp-settings.json.
# gateway, prefix_length, server_host are auto-derived — never entered by the user.
DEFAULT_SETTINGS: dict = {
    "interface":     "eth0",
    "gateway":       "",
    "prefix_length": 24,
    "range_start":   "192.168.1.100",
    "range_end":     "192.168.1.200",
    "lease_time":    "12h",
    "dhcp_dns":      "",
    "server_host":   "",
}

# Interface name prefixes that are never useful for DHCP/PXE
_SKIP_IFACE_PREFIXES = ("lo", "docker", "br-", "veth", "virbr", "tun", "tap")


def _prefix_to_mask(prefix: int) -> str:
    bits = (0xFFFFFFFF << (32 - prefix)) & 0xFFFFFFFF
    return ".".join(str((bits >> (8 * i)) & 0xFF) for i in (3, 2, 1, 0))


def _derive_gateway(ip: str, prefix: int) -> str:
    """Return the .1 address of the subnet containing ip/prefix as a fallback gateway."""
    parts = ip.split(".")
    if len(parts) != 4:
        return ""
    if prefix >= 24:
        return f"{parts[0]}.{parts[1]}.{parts[2]}.1"
    if prefix >= 16:
        return f"{parts[0]}.{parts[1]}.0.1"
    return f"{parts[0]}.0.0.1"


def _docker_client() -> httpx.AsyncClient:
    transport = httpx.AsyncHTTPTransport(uds=DOCKER_SOCKET)
    return httpx.AsyncClient(transport=transport, base_url="http://localhost", timeout=10.0)


def _config_path() -> Path:
    return get_settings().config_dir / "dhcp-settings.json"


def _dnsmasq_conf_path() -> Path:
    return get_settings().config_dir / "dnsmasq.conf"


def load_settings() -> dict:
    path = _config_path()
    if path.exists():
        try:
            stored = json.loads(path.read_text())
            return {**DEFAULT_SETTINGS, **stored}
        except Exception as exc:
            logger.warning("Could not read DHCP settings: %s", exc)
    return dict(DEFAULT_SETTINGS)


def save_settings(settings: dict) -> None:
    """Persist settings to JSON and regenerate dnsmasq.conf."""
    _config_path().write_text(json.dumps(settings, indent=2))
    _write_dnsmasq_conf(settings)
    logger.info("DHCP settings saved to %s", _config_path())


def _write_dnsmasq_conf(settings: dict) -> None:
    cfg         = get_settings()
    server_host = (settings.get("server_host") or "").strip() or cfg.get_server_host()
    interface   = settings.get("interface", "eth0") or "eth0"
    gateway     = (settings.get("gateway") or "").strip()
    prefix      = int(settings.get("prefix_length", 24))
    mask        = _prefix_to_mask(prefix)
    range_start = settings.get("range_start", "192.168.1.100")
    range_end   = settings.get("range_end",   "192.168.1.200")
    lease_time  = settings.get("lease_time",  "12h") or "12h"
    dhcp_range  = f"{range_start},{range_end},{mask},{lease_time}"
    dhcp_dns    = (settings.get("dhcp_dns") or "").strip()
    webui_port  = cfg.webui_port

    router_line = f"dhcp-option=option:router,{gateway}" if gateway else "# gateway not configured"
    dns_line    = f"dhcp-option=option:dns-server,{dhcp_dns}" if dhcp_dns else "# DNS not configured"

    conf = f"""# Generated by eve-ipxe-server DHCP manager — do not edit manually.
interface={interface}
bind-interfaces

# DHCP pool
dhcp-range={dhcp_range}
dhcp-no-override

# Default gateway pushed to clients
{router_line}

# DNS server pushed to clients
{dns_line}

# ── PXE / iPXE boot ──────────────────────────────────────────────────────────
dhcp-option=66,{server_host}
dhcp-boot=undionly.kpxe,{server_host},{server_host}

dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:efi-x86_64,ipxe.efi,{server_host},{server_host}

dhcp-match=set:efi-arm64,option:client-arch,11
dhcp-boot=tag:efi-arm64,ipxe-arm64.efi,{server_host},{server_host}

dhcp-userclass=set:ipxe,iPXE
dhcp-boot=tag:ipxe,http://{server_host}:{webui_port}/ipxe/boot.ipxe

log-queries
log-dhcp
"""
    _dnsmasq_conf_path().write_text(conf)
    logger.info("Generated dnsmasq.conf at %s", _dnsmasq_conf_path())


# ── Host interface detection (via dnsmasq container, which uses host networking) ──

async def _docker_exec(client: httpx.AsyncClient, cmd: list[str]) -> str:
    """Run a command inside the dnsmasq container and return stdout as text."""
    create = await client.post(
        f"/containers/{CONTAINER_NAME}/exec",
        json={"Cmd": cmd, "AttachStdout": True, "AttachStderr": False},
        timeout=5.0,
    )
    if create.status_code != 201:
        return ""
    exec_id = create.json()["Id"]
    start = await client.post(
        f"/exec/{exec_id}/start",
        json={"Detach": False, "Tty": False},
        headers={"Content-Type": "application/json"},
        timeout=5.0,
    )
    return _decode_docker_stream(start.content)


def _decode_docker_stream(data: bytes) -> str:
    """Decode Docker's multiplexed stdout/stderr frame format."""
    parts, i = [], 0
    while i + 8 <= len(data):
        frame_len = int.from_bytes(data[i + 4:i + 8], "big")
        if i + 8 + frame_len > len(data):
            break
        parts.append(data[i + 8:i + 8 + frame_len].decode("utf-8", errors="replace"))
        i += 8 + frame_len
    return "".join(parts)


def _parse_ip_addr(addr_output: str, default_gw: str, default_dev: str) -> list[dict]:
    """Parse `ip -4 addr show` text into a list of interface info dicts."""
    interfaces: list[dict] = []
    current_iface: str | None = None

    for line in addr_output.splitlines():
        # Interface header: "2: eth0: <BROADCAST,MULTICAST,UP,..."
        m = re.match(r"^\d+:\s+(\S+?)(?:@\S+)?:", line)
        if m:
            current_iface = m.group(1)
            continue
        # IP line: "    inet 192.168.1.50/24 brd 192.168.1.255 ..."
        m = re.match(r"^\s+inet\s+(\d+\.\d+\.\d+\.\d+)/(\d+)", line)
        if m and current_iface:
            if any(current_iface.startswith(p) for p in _SKIP_IFACE_PREFIXES):
                continue
            ip, prefix = m.group(1), int(m.group(2))
            # Use the detected default gateway for the primary NIC; derive .1 for others
            if current_iface == default_dev and default_gw:
                gw = default_gw
            else:
                gw = _derive_gateway(ip, prefix)
            interfaces.append({
                "interface":    current_iface,
                "ip":           ip,
                "prefix_length": prefix,
                "gateway":      gw,
            })
    return interfaces


async def get_host_interfaces() -> list[dict]:
    """
    Return the host's IPv4 network interfaces by exec-ing into the dnsmasq
    container (which uses host networking and can see all host NICs).
    Returns an empty list when the container is unavailable.
    """
    try:
        async with _docker_client() as client:
            # Detect default gateway and primary NIC
            route_out = await _docker_exec(client, ["ip", "route", "show", "default"])
            gw_m   = re.search(r"default via (\S+)", route_out)
            dev_m  = re.search(r"dev (\S+)",         route_out)
            default_gw  = gw_m.group(1)  if gw_m  else ""
            default_dev = dev_m.group(1) if dev_m else ""

            addr_out = await _docker_exec(client, ["ip", "-4", "addr", "show"])
            return _parse_ip_addr(addr_out, default_gw, default_dev)
    except Exception as exc:
        logger.warning("Could not detect host interfaces: %s", exc)
        return []


# ── Container lifecycle ───────────────────────────────────────────────────────

async def get_container_status() -> dict:
    conf_exists = _dnsmasq_conf_path().exists()
    try:
        async with _docker_client() as client:
            resp = await client.get(f"/containers/{CONTAINER_NAME}/json")
            if resp.status_code == 404:
                return {"available": False, "running": False, "status": "not_found",
                        "configured": conf_exists,
                        "error": "Container not found — ensure docker-compose includes the dnsmasq service"}
            resp.raise_for_status()
            data  = resp.json()
            state = data.get("State", {})
            return {
                "available":   True,
                "running":     state.get("Running", False),
                "status":      state.get("Status", "unknown"),
                "configured":  conf_exists,
                "started_at":  state.get("StartedAt"),
                "finished_at": state.get("FinishedAt"),
            }
    except httpx.TransportError:
        return {"available": False, "running": False, "status": "error",
                "configured": conf_exists,
                "error": "Docker socket not accessible — is /var/run/docker.sock mounted?"}
    except Exception as exc:
        logger.warning("Docker API error: %s", exc)
        return {"available": False, "running": False, "status": "error",
                "configured": conf_exists, "error": str(exc)}


async def start_container() -> None:
    async with _docker_client() as client:
        info = await client.get(f"/containers/{CONTAINER_NAME}/json")
        if info.status_code == 200 and info.json().get("State", {}).get("Running"):
            resp = await client.post(f"/containers/{CONTAINER_NAME}/restart", params={"t": 5})
        else:
            resp = await client.post(f"/containers/{CONTAINER_NAME}/start")
        if resp.status_code not in (204, 304):
            raise RuntimeError(f"Docker API returned {resp.status_code}: {resp.text}")


async def stop_container() -> None:
    async with _docker_client() as client:
        resp = await client.post(f"/containers/{CONTAINER_NAME}/stop", params={"t": 5})
        if resp.status_code not in (204, 304):
            raise RuntimeError(f"Docker API returned {resp.status_code}: {resp.text}")


async def restart_container() -> None:
    async with _docker_client() as client:
        resp = await client.post(f"/containers/{CONTAINER_NAME}/restart", params={"t": 5})
        if resp.status_code not in (204,):
            raise RuntimeError(f"Docker API returned {resp.status_code}: {resp.text}")
