"""
DHCP server manager — controls the eve-ipxe-dnsmasq container via the
Docker Engine API (Unix socket) and manages the dnsmasq configuration.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

import httpx

from app.config import get_settings

logger = logging.getLogger(__name__)

DOCKER_SOCKET = "/var/run/docker.sock"
CONTAINER_NAME = "eve-ipxe-dnsmasq"

DEFAULT_SETTINGS: dict = {
    "interface":    "eth0",
    "gateway":      "",               # router IP — subnet anchor + pushed to clients
    "prefix_length": 24,              # CIDR prefix, e.g. 24 → 255.255.255.0
    "range_start":  "192.168.1.100",
    "range_end":    "192.168.1.200",
    "lease_time":   "12h",
    "dhcp_dns":     "",
    "server_host":  "",
}


def _prefix_to_mask(prefix: int) -> str:
    """Convert a CIDR prefix length to a dotted-decimal subnet mask."""
    bits = (0xFFFFFFFF << (32 - prefix)) & 0xFFFFFFFF
    return ".".join(str((bits >> (8 * i)) & 0xFF) for i in (3, 2, 1, 0))


def _docker_client() -> httpx.AsyncClient:
    transport = httpx.AsyncHTTPTransport(uds=DOCKER_SOCKET)
    return httpx.AsyncClient(transport=transport, base_url="http://localhost", timeout=10.0)


def _config_path() -> Path:
    return get_settings().config_dir / "dhcp-settings.json"


def _dnsmasq_conf_path() -> Path:
    return get_settings().config_dir / "dnsmasq.conf"


def load_settings() -> dict:
    """Load DHCP settings from the config file, falling back to defaults."""
    path = _config_path()
    if path.exists():
        try:
            stored = json.loads(path.read_text())
            # Merge with defaults so new keys are always present
            return {**DEFAULT_SETTINGS, **stored}
        except Exception as exc:
            logger.warning("Could not read DHCP settings: %s", exc)
    return dict(DEFAULT_SETTINGS)


def save_settings(settings: dict) -> None:
    """Persist settings to JSON and regenerate dnsmasq.conf."""
    _config_path().write_text(json.dumps(settings, indent=2))
    _write_dnsmasq_conf(settings)
    logger.info("DHCP settings saved to %s", _config_path())


def _write_dnsmasq_conf(settings: dict) -> None:
    """Generate a dnsmasq.conf from settings and write to the config volume."""
    cfg         = get_settings()
    server_host = (settings.get("server_host") or "").strip() or cfg.get_server_host()
    interface   = settings.get("interface", "eth0") or "eth0"
    gateway     = (settings.get("gateway") or "").strip()
    prefix      = int(settings.get("prefix_length", 24))
    mask        = _prefix_to_mask(prefix)
    range_start = settings.get("range_start", "192.168.1.100")
    range_end   = settings.get("range_end",   "192.168.1.200")
    lease_time  = settings.get("lease_time",  "12h") or "12h"
    dhcp_range  = f"{range_start},{range_end},{mask},{lease_time}"
    dhcp_dns    = (settings.get("dhcp_dns") or "").strip()
    webui_port  = cfg.webui_port

    router_line = f"dhcp-option=option:router,{gateway}" if gateway else "# gateway not configured"
    dns_line    = f"dhcp-option=option:dns-server,{dhcp_dns}" if dhcp_dns else "# DHCP_DNS not configured"

    conf = f"""# Generated by eve-ipxe-server DHCP manager — do not edit manually.
# Regenerated every time settings are saved from the web UI.
interface={interface}
bind-interfaces

# DHCP pool
dhcp-range={dhcp_range}
dhcp-no-override

# Optional: push default gateway to clients
{router_line}

# Optional: push DNS server to clients
{dns_line}

# ── PXE / iPXE boot ──────────────────────────────────────────────────────────
# TFTP server address (DHCP option 66)
dhcp-option=66,{server_host}

# BIOS PXE clients — receive undionly.kpxe which chainloads iPXE
dhcp-boot=undionly.kpxe,{server_host},{server_host}

# UEFI x86_64 clients (arch 7) — receive ipxe.efi
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:efi-x86_64,ipxe.efi,{server_host},{server_host}

# UEFI arm64 clients (arch 11) — receive ipxe-arm64.efi
dhcp-match=set:efi-arm64,option:client-arch,11
dhcp-boot=tag:efi-arm64,ipxe-arm64.efi,{server_host},{server_host}

# iPXE clients — redirect straight to the HTTP boot script
dhcp-userclass=set:ipxe,iPXE
dhcp-boot=tag:ipxe,http://{server_host}:{webui_port}/ipxe/boot.ipxe

# Logging
log-queries
log-dhcp
"""
    _dnsmasq_conf_path().write_text(conf)
    logger.info("Generated dnsmasq.conf at %s", _dnsmasq_conf_path())


async def get_container_status() -> dict:
    """Query the Docker Engine API for the dnsmasq container state."""
    conf_exists = _dnsmasq_conf_path().exists()
    try:
        async with _docker_client() as client:
            resp = await client.get(f"/containers/{CONTAINER_NAME}/json")
            if resp.status_code == 404:
                return {"available": False, "running": False, "status": "not_found",
                        "configured": conf_exists,
                        "error": "Container not found — ensure docker-compose includes the dnsmasq service"}
            resp.raise_for_status()
            data  = resp.json()
            state = data.get("State", {})
            return {
                "available":   True,
                "running":     state.get("Running", False),
                "status":      state.get("Status", "unknown"),
                "configured":  conf_exists,
                "started_at":  state.get("StartedAt"),
                "finished_at": state.get("FinishedAt"),
            }
    except httpx.TransportError:
        return {"available": False, "running": False, "status": "error",
                "configured": conf_exists,
                "error": "Docker socket not accessible — is /var/run/docker.sock mounted?"}
    except Exception as exc:
        logger.warning("Docker API error: %s", exc)
        return {"available": False, "running": False, "status": "error",
                "configured": conf_exists, "error": str(exc)}


async def start_container() -> None:
    """Start (or restart if idle) the dnsmasq container so it picks up the current config."""
    async with _docker_client() as client:
        # Check current state — if already running in idle mode, restart to pick up new config
        info = await client.get(f"/containers/{CONTAINER_NAME}/json")
        if info.status_code == 200 and info.json().get("State", {}).get("Running"):
            resp = await client.post(f"/containers/{CONTAINER_NAME}/restart", params={"t": 5})
        else:
            resp = await client.post(f"/containers/{CONTAINER_NAME}/start")
        if resp.status_code not in (204, 304):
            raise RuntimeError(f"Docker API returned {resp.status_code}: {resp.text}")


async def stop_container() -> None:
    async with _docker_client() as client:
        resp = await client.post(f"/containers/{CONTAINER_NAME}/stop", params={"t": 5})
        if resp.status_code not in (204, 304):
            raise RuntimeError(f"Docker API returned {resp.status_code}: {resp.text}")


async def restart_container() -> None:
    async with _docker_client() as client:
        resp = await client.post(f"/containers/{CONTAINER_NAME}/restart", params={"t": 5})
        if resp.status_code not in (204,):
            raise RuntimeError(f"Docker API returned {resp.status_code}: {resp.text}")
